<script src="../jQuery/jquery-2.1.3.min.js" type="text/javascript"></script>
<link href="../css/global.css" type="text/css" rel="stylesheet">
<script src="../jQuery/bootstrap-3.3.7-dist/js/bootstrap.js" type="text/javascript"></script>
<link href="../jQuery/bootstrap-3.3.7-dist/css/bootstrap.css" type="text/css" rel="stylesheet">
<link href="../jQuery/bootstrap-3.3.7-dist/css/bootstrap-theme.css" type="text/css" rel="stylesheet">
